name: loccon
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+23

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_dynamic_links: ^0.7.0+1
  google_sign_in: ^4.5.9
  http: ^0.12.2
  image_picker: ^0.6.7+21
  multi_image_picker: ^4.7.14
  onesignal_flutter: ^2.6.2
  share: ^0.6.5+4
  shared_preferences: ^2.0.8
  timeago: ^2.0.29
  youtube_player_flutter: ^7.0.0+7

  url_launcher: ^5.7.2
  package_info: ^2.0.2
  firebase_remote_config: ^0.6.0

  fluttertoast: ^8.0.8
  firebase_analytics: any
  material_segmented_control: ^3.1.2
  photo_view: ^0.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/loccon.png
    - assets/avatar.png
    - assets/splashbg.jpg
    - assets/logo_icon.png
    - assets/events_icon.png
    - assets/profile_icon.png
    - assets/msg_icon.png
    - assets/intro1.jpg
    - assets/intro2.jpg
    - assets/intro3.jpg
    - assets/icon_google.png
    - assets/icon_phone.png
    - assets/new_post.png
    - assets/chat.png
    - assets/event.png
    - assets/man.png
    - assets/user.png
    - assets/plus.png
    - assets/calendar.png
    - assets/add.png
    - assets/loading.gif
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
